# Generated by Django 2.1.3 on 2019-09-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Family_Name', models.CharField(blank=True, max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
