# Generated by Django 2.1.3 on 2019-09-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='Number_Of_Adults',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='Number_Of_Kids',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
