# Generated by Django 2.1.3 on 2019-09-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolioImage',
            new_name='portfolio_image',
        ),
    ]
